-- MySQL Script generated by MySQL Workbench
-- Thu Dec  7 23:38:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(155) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(400) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(155) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(100) NOT NULL,
  `endereco` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(155) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(400) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `ativo` TINYINT NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `admin_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_mecanico_admin1_idx` (`admin_id` ASC) VISIBLE,
  CONSTRAINT `fk_mecanico_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `mydb`.`admin` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipe` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(155) NOT NULL,
  `funcao` TEXT NOT NULL,
  `funcionario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_equipe_funcionario1_idx` (`funcionario_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipe_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `mydb`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(45) NOT NULL,
  `cor` VARCHAR(100) NOT NULL,
  `modelo` VARCHAR(100) NOT NULL,
  `ano` INT NOT NULL,
  `cliente_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_veiculo_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mydb`.`cliente` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`ordemservico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordemservico` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `solucao` TEXT NOT NULL,
  `defeito` INT NOT NULL,
  `data_entrada` DATE NOT NULL,
  `data_saida` DATE NOT NULL,
  `equipe_id` INT UNSIGNED NOT NULL,
  `cliente_id` INT UNSIGNED NOT NULL,
  `veiculo_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_ordemServico_equipe1_idx` (`equipe_id` ASC) VISIBLE,
  INDEX `fk_ordemServico_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_ordemServico_veiculo1_idx` (`veiculo_id` ASC) VISIBLE,
  CONSTRAINT `fk_ordemServico_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mydb`.`cliente` (`id`),
  CONSTRAINT `fk_ordemServico_equipe1`
    FOREIGN KEY (`equipe_id`)
    REFERENCES `mydb`.`equipe` (`id`),
  CONSTRAINT `fk_ordemServico_veiculo1`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `mydb`.`veiculo` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`peca` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(155) NOT NULL,
  `valor` FLOAT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`ordem_servico_peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordem_servico_peca` (
  `ordem_servico_id` INT UNSIGNED NOT NULL,
  `peca_id` INT UNSIGNED NOT NULL,
  INDEX `fk_ordemServico_has_peca_peca1_idx` (`peca_id` ASC) VISIBLE,
  INDEX `fk_ordemServico_has_peca_ordemServico1_idx` (`ordem_servico_id` ASC) VISIBLE,
  CONSTRAINT `fk_ordemServico_has_peca_ordemServico1`
    FOREIGN KEY (`ordem_servico_id`)
    REFERENCES `mydb`.`ordemservico` (`id`),
  CONSTRAINT `fk_ordemServico_has_peca_peca1`
    FOREIGN KEY (`peca_id`)
    REFERENCES `mydb`.`peca` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
